### ISSUE TITLE
Support the newest tensorflow

### ISSUE THREAD

**Issue by rylanchiu** [TellinaTool/awesome_nmt#1]
Hi! I found your code really useful and amazing! I wonder would you consider update to tensorflow r-1.2? Thx!

**Comment by todpole3** [comment]
Hi,

Yes, we are using r1.2 at this moment. Have you met any problem?

**Comment by rylanchiu** [comment]
@todpole3  Thanks for reply. I thought you were using old version of tf since you implement the rnn cell with attention yourself. Could you please tell me why didn't you use the newest `attention_wrapper` and `attention_mechanism`?

**Comment by todpole3** [comment]
I customized the code because it's easier for me to experiment with different attention formulations.

**Comment by rylanchiu** [comment]
Got it. I tried to run the code on my own data set to get a try. But seems that your data reader functions are quite complicated for different kinds of raw data. I simply split the data into `source.nl` and `target.cm` under the same folder named `dummy`, one of available data set name according to your code. And this folder is placed in the `data`. I changed the dataset to `dummy`  also in the `parse_args`. And I set `use_copy` to true. I run the `./bash-run` for data processing, but meet such an error: 

    Traceback (most recent call last):
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
    File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 628, in <module>
    tf.app.run()
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
    File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 573, in main
    process_data()
    File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 510, in process_data
    data_utils.prepare_data(FLAGS)
    File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/data_utils.py", line 1166, in prepare_data
    prepare_jobs(FLAGS)
    File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/data_utils.py", line 725, in prepare_jobs
    _ = prepare_dataset(nl_list, data_dir, nl_suffix, nl_vocab_size, None)
    File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/data_utils.py", line 553, in prepare_dataset
    if isinstance(data.train[0], list):

Seems that I have missed sth hence nothing is appened to the list. Could you please tell me how should I configure my data set? Did I do sth wrong? Thanks!

**Comment by rylanchiu** [comment]
BTW, my data set is of summarisation tasks.

**Comment by rylanchiu** [comment]
I fixed the data issue already. Just change the suffix of the file. But after setting `use_copy` to true, I got the shape error:

    Traceback (most recent call last):
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
        input_tensors_as_shapes, status)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/contextlib.py", line 66, in __exit__
        next(self.gen)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
        pywrap_tensorflow.TF_GetCode(status))
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 300 and 600 for 'token_decoder_decoder_rnn/mul_1' (op: 'Mul') with input shapes: [?,300], [1,600].

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/runpy.py", line 184, in _run_module_as_main
        "__main__", mod_spec)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 628, in <module>
        tf.app.run()
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
        _sys.exit(main(_sys.argv[:1] + flags_passthrough))
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 616, in main
        train(train_set, dataset)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 69, in train
        model = create_model(sess, forward_only=False)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 57, in create_model
        session, FLAGS, Seq2SeqModel, buckets, forward_only)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/graph_utils.py", line 146, in create_model
        model = model_constructor(params, buckets)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/seq2seq/seq2seq_model.py", line 28, in __init__
        super(Seq2SeqModel, self).__init__(hyperparams, buckets)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/framework.py", line 71, in __init__
        self.define_graph()
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/framework.py", line 169, in define_graph
        self.target_weights[:bucket[1]],
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/framework.py", line 269, in encode_decode
        encoder_copy_inputs=self.encoder_full_inputs)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/seq2seq/rnn_decoder.py", line 155, in define_graph
        decoder_cell(input_embedding, state)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/decoder.py", line 119, in __call__
        self.cell(input_embedding, state, scope)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/decoder.py", line 268, in __call__
        cell_output, state = self.cell(input_embedding, state, scope)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 751, in __call__
        self._input_keep_prob)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 741, in _dropout
        return _enumerated_map_structure(dropout, values, recurrent_noise)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 597, in _enumerated_map_structure
        return nest.map_structure(enumerated_fn, *args, **kwargs)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/util/nest.py", line 325, in map_structure
        structure[0], [func(*x) for x in entries])
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/util/nest.py", line 325, in <listcomp>
        structure[0], [func(*x) for x in entries])
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 594, in enumerated_fn
        r = map_fn(ix[0], *inner_args, **inner_kwargs)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 740, in dropout
        return self._variational_recurrent_dropout_value(i, v, n, keep_prob)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 727, in _variational_recurrent_dropout_value
        ret = math_ops.div(value, keep_prob) * binary_tensor
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 838, in binary_op_wrapper
        return func(x, y, name=name)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1061, in _mul_dispatch
        return gen_math_ops._mul(x, y, name=name)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1377, in _mul
        result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
        op_def=op_def)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
        set_shapes_for_outputs(ret)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
        shapes = shape_func(op)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
        return call_cpp_shape_fn(op, require_shape_fn=True)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
        debug_python_shape_fn, require_shape_fn)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
        raise ValueError(err.message)
    ValueError: Dimensions must be equal, but are 300 and 600 for 'token_decoder_decoder_rnn/mul_1' (op: 'Mul') with input shapes: [?,300], [1,600].

Seems that you need to make some adjustment for the attention and copy states?

**Comment by rylanchiu** [comment]
The `./bash-copy.sh` cause another shape error:

    Traceback (most recent call last):
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/runpy.py", line 184, in _run_module_as_main
        "__main__", mod_spec)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 628, in <module>
        tf.app.run()
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
        _sys.exit(main(_sys.argv[:1] + flags_passthrough))
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 616, in main
        train(train_set, dataset)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 69, in train
        model = create_model(sess, forward_only=False)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/translate.py", line 57, in create_model
        session, FLAGS, Seq2SeqModel, buckets, forward_only)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/graph_utils.py", line 146, in create_model
        model = model_constructor(params, buckets)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/seq2seq/seq2seq_model.py", line 28, in __init__
        super(Seq2SeqModel, self).__init__(hyperparams, buckets)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/framework.py", line 71, in __init__
        self.define_graph()
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/framework.py", line 169, in define_graph
        self.target_weights[:bucket[1]],
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/framework.py", line 269, in encode_decode
        encoder_copy_inputs=self.encoder_full_inputs)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/seq2seq/rnn_decoder.py", line 151, in define_graph
        decoder_cell(input_embedding, state)
      File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/decoder.py", line 136, in __call__
        tf.one_hot(self.encoder_inputs, self.tg_vocab_size)), 1)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1786, in matmul
        a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 290, in _batch_mat_mul
        adj_y=adj_y, name=name)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
        op_def=op_def)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
        set_shapes_for_outputs(ret)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
        shapes = shape_func(op)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
        return call_cpp_shape_fn(op, require_shape_fn=True)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
        debug_python_shape_fn, require_shape_fn)
      File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
        raise ValueError(err.message)
    ValueError: Dimensions must be equal, but are 20 and 45 for 'token_decoder_decoder_rnn/MatMul_1' (op: 'BatchMatMul') with input shapes: [128,1,20], [?,45,3045].

I wonder whether you have run the experiment on non-bash data?

**Comment by rylanchiu** [comment]
Oh it is quite tricky... I changed the bucket size and error changed again...

    File "/Users/yobichi/textsum/awesome_nmt-master/encoder_decoder/decoder.py", line 125, in __call__
      gen_logit = tf.matmul(output, W) + b - 1e12 * (1 - self.generation_mask)
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 838, in binary_op_wrapper
      return func(x, y, name=name)
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2501, in _sub
      result = _op_def_lib.apply_op("Sub", x=x, y=y, name=name)
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
      op_def=op_def)
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
      set_shapes_for_outputs(ret)
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
      shapes = shape_func(op)
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
      return call_cpp_shape_fn(op, require_shape_fn=True)
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
      debug_python_shape_fn, require_shape_fn)
    File "/Users/yobichi/miniconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
      raise ValueError(err.message)
  ValueError: Dimensions must be equal, but are 3040 and 3045 for 'token_decoder_decoder_rnn/sub' (op: 'Sub') with input shapes: [128,3040], [3045].

**Comment by todpole3** [comment]
@rylanchiu Sorry for all the hassles. I'll trouble shoot the code today and get back to you.

**Comment by rylanchiu** [comment]
@todpole3  Thanks for your work. Seems that I need to re-`process` the data before I retrain the model. But now it has a indice error, that is, a number larger than the vocab size is feed for `embedding_lookup`.

**Comment by todpole3** [comment]
The data processing pipeline has been reimplemented.
